services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      NEXT_PUBLIC_API_URL: http://backend:8000

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  backend:
      container_name: fastapi-backend
      build:
        context: ./backend
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      volumes:
        - ./backend/app:/app/app
      ports:
        - 8000:8000
      restart: always
      networks:
        - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
